; DefaultEditor.ini
; ═══════════════════════════════════════════════════════════════════════════
;  Configuración del editor — AlsasuaSimulator
; ═══════════════════════════════════════════════════════════════════════════

[/Script/UnrealEd.EditorEngine]
bSmoothFrameRate=True
bAutoCompileBlueprints=False

[/Script/UnrealEd.PerProjectDebugSettings]
; Desactivar Live Coding en el editor
EditorPerformanceSettings=(bShowLiveCodingConsole=False)

[/Script/UnrealEd.EditorPerProjectUserSettings]
